# -*- coding: utf-8 -*-
"""Hw2APPM4600.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HOTHJPCmfx9EoXwpT5AJu7FVSaMdIcRD
"""

import numpy as np
import matplotlib.pyplot as plt
import random
#Q2
a = np.array([[1, 1], [1+10**(-10), 1-10**(-10)]])
[U, S, Vh] = np.linalg.svd(a)


DelB1 = 5*10**(-5)
DelB2 = 5*10**(-5)

delx = [(1+DelB1)*(1-10**10)+(1+DelB2)*(10**10), (1+DelB1)*(1+10**10)-(1+DelB2)*(10**10)]


#Q3
#x = np.arange(-.005,.005,.000001)
x = 9.999999995000000*10**(-10)
#y = np.exp(x)
#f = y-1
f = x
f




#plt.plot(x, f)
#plt.xlabel("x")
#plt.ylabel("f(x)")

#plt.show()


#Q4a
t = np.arange(0,np.pi,np.pi/30)
y = np.cos(t)
N = len(t)
sum = 0
for k in range(N):
  sum = sum + t[k]*y[k]

print("The sum is: ", sum)


#Q4b
theta = np.arange(0,2*np.pi, .001)
R = 1.2
delr = 0.1
l = 15
p = 0
xtheta = R*(1+delr*np.sin(l*theta+p))*np.cos(theta)
ytheta = R*(1+delr*np.sin(l*theta+p))*np.sin(theta)

plt.clf()
plt.plot(theta, xtheta)
plt.plot(theta,ytheta)

plt.clf

for i in range(10):
  R = i
  delr = 0.05
  l = 2+i
  p = random.uniform(0, 2)
  xtheta = R*(1+delr*np.sin(l*theta+p))*np.cos(theta)
  ytheta = R*(1+delr*np.sin(l*theta+p))*np.sin(theta)

  plt.plot(theta, xtheta)
  plt.plot(theta, ytheta)

plt.show